name: build and publish to nuget
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # NOW CAN YOU PLEASE FUCKING WORK?
      - name: Build librabbitizer.so
        run: |
          sudo apt-get install -y clang
          mkdir -p native_build
          clang -shared -fPIC -std=c11 -I rabbitizer/include -I rabbitizer/tables $(find rabbitizer/src -name "*.c") -o native_build/librabbitizer.so
      - uses: actions/upload-artifact@v4
        with:
          name: native-linux-x64
          path: native_build/librabbitizer.so

  build-linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build librabbitizer.so
        run: |
          sudo apt-get install -y clang
          mkdir -p native_build
          clang -shared -fPIC -std=c11 -I rabbitizer/include -I rabbitizer/tables $(find rabbitizer/src -name "*.c") -o native_build/librabbitizer.so
      - uses: actions/upload-artifact@v4
        with:
          name: native-linux-arm64
          path: native_build/librabbitizer.so

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build librabbitizer.dylib
        run: |
          mkdir -p native_build
          clang -dynamiclib -std=c11 -I rabbitizer/include -I rabbitizer/tables $(find rabbitizer/src -name "*.c") -o native_build/librabbitizer.dylib
      - uses: actions/upload-artifact@v4
        with:
          name: native-osx-arm64
          path: native_build/librabbitizer.dylib

  build-windows-x64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          install: mingw-w64-clang-x86_64-clang
      - name: Build rabbitizer.dll
        run: |
          mkdir -p native_build
          clang -shared -std=c11 -I rabbitizer/include -I rabbitizer/tables $(find rabbitizer/src -name "*.c") -o native_build/rabbitizer.dll
      - uses: actions/upload-artifact@v4
        with:
          name: native-win-x64
          path: native_build/rabbitizer.dll

  pack-and-publish:
    needs:
      - build-linux-x64
      - build-linux-arm64
     # - build-macos-x64 # removed because the runner wont.. well.. run
      - build-macos-arm64
      - build-windows-x64
      # removed windows arm until i figure out how to make it work
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: place libs on the folder
        run: |
          mkdir -p src/RabbitizerSharp/runtimes/linux-x64/native
          mkdir -p src/RabbitizerSharp/runtimes/linux-arm64/native
          mkdir -p src/RabbitizerSharp/runtimes/osx-x64/native
          mkdir -p src/RabbitizerSharp/runtimes/osx-arm64/native
          mkdir -p src/RabbitizerSharp/runtimes/win-x64/native
          mkdir -p src/RabbitizerSharp/runtimes/win-arm64/native
          cp artifacts/native-linux-x64/librabbitizer.so    src/RabbitizerSharp/runtimes/linux-x64/native/librabbitizer.so
          cp artifacts/native-linux-arm64/librabbitizer.so  src/RabbitizerSharp/runtimes/linux-arm64/native/librabbitizer.so
          cp artifacts/native-osx-x64/librabbitizer.dylib   src/RabbitizerSharp/runtimes/osx-x64/native/librabbitizer.dylib
          cp artifacts/native-osx-arm64/librabbitizer.dylib src/RabbitizerSharp/runtimes/osx-arm64/native/librabbitizer.dylib
          cp artifacts/native-win-x64/rabbitizer.dll        src/RabbitizerSharp/runtimes/win-x64/native/rabbitizer.dll
          cp artifacts/native-win-arm64/rabbitizer.dll      src/RabbitizerSharp/runtimes/win-arm64/native/rabbitizer.dll

      - name: extract version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: pack
        run: dotnet pack src/RabbitizerSharp/RabbitizerSharp.csproj -c Release -p:Version=${{ steps.version.outputs.VERSION }} -o ./nupkg

      - name: publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate